staging: mali: Disable unsupported r5p2 version
r5p2 misses Xilinx init code. Disabling this version till this support
is added.

Compilation error:
drivers/staging/mali/DX910-SW-99002-r5p2-00rel0/driver/src/devicedrv/mali/linux/mali_kernel_linux.o
drivers/staging/mali/DX910-SW-99002-r5p2-00rel0/driver/src/devicedrv/mali/linux/mali_kernel_linux.c:
In function ‘mali_probe’:
drivers/staging/mali/DX910-SW-99002-r5p2-00rel0/driver/src/devicedrv/mali/linux/mali_kernel_linux.c:475:2:
error: implicit declaration of function ‘mali_platform_device_init’
[-Werror=implicit-function-declaration]
  err = mali_platform_device_init(mali_platform_device);
  ^
drivers/staging/mali/DX910-SW-99002-r5p2-00rel0/driver/src/devicedrv/mali/linux/mali_kernel_linux.c:
In function ‘mali_remove’:
drivers/staging/mali/DX910-SW-99002-r5p2-00rel0/driver/src/devicedrv/mali/linux/mali_kernel_linux.c:521:2:
error: implicit declaration of function ‘mali_platform_device_deinit’
[-Werror=implicit-function-declaration]
  mali_platform_device_deinit(mali_platform_device);
  ^
cc1: some warnings being treated as errors

Reported-by: Christian Kohn <christian.kohn@xilinx.com>
Reported-by: Hyun Kwon <hyun.kwon@xilinx.com>
Signed-off-by: Michal Simek <michal.simek@xilinx.com>