iio: versal-sysmon: Add missing EXPORT_SYMBOL_GPL
sysmon_create_avg_en_sysfs_entries() is used by versal sysmon driver
and result in below undefined error when CONFIG_VERSAL_SYSMON=m.
To fix it add EXPORT_SYMBOL_GPL symbol.

ERROR: modpost: "sysmon_create_avg_en_sysfs_entries"
 [drivers/iio/adc/versal-sysmon.ko] undefined!
make[2]: *** [scripts/Makefile.modpost:145: Module.symvers] Error 1
make[1]: *** [linux-xlnx/Makefile:1888: modpost] Error 2
make: *** [Makefile:224: __sub-make] Error 2

Signed-off-by: Radhey Shyam Pandey <radhey.shyam.pandey@amd.com>