ARM: Add local tick_receive_broadcast_local()
Handler function is defined as void (*handler)(void)

tick_receive_broadcast is returning int instead of void
which is showed by compilation error:
arch/arm/kernel/smp.c:509:2: warning: initialization from incompatible
pointer type
  S(IPI_TIMER, tick_receive_broadcast),
  ^
arch/arm/kernel/smp.c:509:2: warning: (near initialization for
'ipi_types[1].handler')

This patch creates local version of this function to avoid
compilation warning.

Signed-off-by: Michal Simek <michal.simek@xilinx.com>