usb: dwc3: fix a build error when CONFIG_PM is not set.
There is a build error when CONFIG_PM is not set:
dwc3-of-simple.c:544:3: error: implicit declaration of function
'dwc3_simple_vbus';

Since dwc3_simple_vbus is defined only when CONFIG_PM is set, it
should be invoked when CONFIG_PM is set.

Signed-off-by: zheng.wang <zheng.wang@calmcar.com>
Signed-off-by: yongtong.yao <yongtong.yao@calmcar.com>