v4l2: Add missing of_graph.h to fix multi_v7_defconfig build failure
This patch should be the part of:
"Merge tag 'v4.0' into master"
(sha1: 7aaad3af48aecef823ed2eb72b09863d9ca80593)

Warning log:
  drivers/media/platform/soc_camera/soc_camera.c: In function
‘scan_of_host’:
  drivers/media/platform/soc_camera/soc_camera.c:1682:3: error: implicit
declaration of function ‘of_graph_get_next_endpoint’
[-Werror=implicit-function-declaration]
     epn = of_graph_get_next_endpoint(np, epn);
     ^
  drivers/media/platform/soc_camera/soc_camera.c:1682:7: warning:
assignment makes pointer from integer without a cast
     epn = of_graph_get_next_endpoint(np, epn);
         ^
  drivers/media/platform/soc_camera/soc_camera.c:1686:3: error: implicit
declaration of function ‘of_graph_get_remote_port’
[-Werror=implicit-function-declaration]
     ren = of_graph_get_remote_port(epn);
     ^
  drivers/media/platform/soc_camera/soc_camera.c:1686:7: warning:
assignment makes pointer from integer without a cast
     ren = of_graph_get_remote_port(epn);

Signed-off-by: Michal Simek <michal.simek@xilinx.com>