PM / Hibernate: Add missing header
This fixes the compilation errors:
  kernel/power/hibernate.c: In function ‘create_image’:
  kernel/power/hibernate.c:286:2: error: implicit declaration of function ‘clockevents_notify’ [-Werror=implicit-function-declaration]
    clockevents_notify(CLOCK_EVT_NOTIFY_SUSPEND, NULL);
    ^
  kernel/power/hibernate.c:286:21: error: ‘CLOCK_EVT_NOTIFY_SUSPEND’ undeclared (first use in this function)
    clockevents_notify(CLOCK_EVT_NOTIFY_SUSPEND, NULL);
                       ^
  kernel/power/hibernate.c:286:21: note: each undeclared identifier is reported only once for each function it appears in
  kernel/power/hibernate.c:319:21: error: ‘CLOCK_EVT_NOTIFY_RESUME’ undeclared (first use in this function)
    clockevents_notify(CLOCK_EVT_NOTIFY_RESUME, NULL);
                       ^
  kernel/power/hibernate.c: In function ‘resume_target_kernel’:
  kernel/power/hibernate.c:442:21: error: ‘CLOCK_EVT_NOTIFY_SUSPEND’ undeclared (first use in this function)
    clockevents_notify(CLOCK_EVT_NOTIFY_SUSPEND, NULL);
                       ^
  kernel/power/hibernate.c:478:21: error: ‘CLOCK_EVT_NOTIFY_RESUME’ undeclared (first use in this function)
    clockevents_notify(CLOCK_EVT_NOTIFY_RESUME, NULL);
                       ^
  kernel/power/hibernate.c: In function ‘hibernation_platform_enter’:
  kernel/power/hibernate.c:563:21: error: ‘CLOCK_EVT_NOTIFY_SUSPEND’ undeclared (first use in this function)
    clockevents_notify(CLOCK_EVT_NOTIFY_SUSPEND, NULL);
                       ^
  kernel/power/hibernate.c:578:21: error: ‘CLOCK_EVT_NOTIFY_RESUME’ undeclared (first use in this function)
    clockevents_notify(CLOCK_EVT_NOTIFY_RESUME, NULL);
                       ^

Reported-by: Cyril Chemparathy <cyril.chemparathy@xilinx.com>
Signed-off-by: Soren Brinkmann <soren.brinkmann@xilinx.com>
Signed-off-by: Michal Simek <michal.simek@xilinx.com>