drm: xlnx: hdcp: Add missing slab.h include
This fixes the following build error:
drivers/gpu/drm/xlnx/hdcp/xlnx_hdcp2x_tx.c:614:18: error: implicit
declaration of function 'kzalloc'

Signed-off-by: Rajesh Gugulothu <rajesh.gugulothu@amd.com>
Message-ID: <20260224132312.800533-3-rajesh.gugulothu@amd.com>
State: pending