phy: xilinx-xhdmiphy: Fix compilation errors
Remove xhdmiphy_set and xhdmiphy_clr functions from xhdmiphy_modules.c
file because these are implemented already in xhdmiphy_core.c file.
Implementing them again in xhdmiphy_modules.c file causes compilation
errors. Fixes below error log:

linux-xlnx/drivers/phy/xilinx/xhdmiphy.c: In function 'xhdmiphy_configure':
linux-xlnx/drivers/phy/xilinx/xhdmiphy.c:225:25: error: implicit
declaration of function 'xhdmiphy_set'; did you mean 'xhdmiphy_reset'?
[-Werror=implicit-function-declaration]

<snip>
linux-xlnx/drivers/phy/xilinx/xhdmiphy.c:227:25: error: implicit
declaration of function 'xhdmiphy_clr'; did you mean 'xhdmiphy_init'?
[-Werror=implicit-function-declaration]

Signed-off-by: Rajesh Gugulothu <rajesh.gugulothu@amd.com>
Reviewed-by: Vishal Sagar <vishal.sagar@amd.com>
Signed-off-by: Radhey Shyam Pandey <radhey.shyam.pandey@amd.com>