udc: zynq: Remove compilation error when CONFIG_PROVE_LOCKING is used
Compilation error:
`zynq_udc_remove' referenced in section `.data' of drivers/built-in.o:
defined in discarded section `.exit.text' of drivers/built-in.o

Signed-off-by: Michal Simek <michal.simek@xilinx.com>