misc: xilinx-ai-engine: fix compile error due to incorrect arg type
The argument "attr" to sysfs_attr_init is "struct attribute *" type
not "struct device_attribute *" type. This patch fixes the compile
error as below:

drivers/misc/xilinx-ai-engine/ai-engine-sysfs.c: In function ‘aie_sysfs_create_dev_attr’:
/home/wrsadmin/repos/linux/include/linux/sysfs.h:55:8: error: ‘struct device_attribute’ has no member named ‘key’
   55 |  (attr)->key = &__key;    \
      |        ^~

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
State: pending