microblaze: add <asm/barrier.h> to <asm/bitops.h>
The "smp_store_release" is defined in include/asm-generic/barrier.h
which is included by arch/microblaze/include/asm/barrier.h.
When we use gcc to preprocess asm-offsets.c to .i file, we can see that
none of the header files included before list.h contains "asm/barrier.h",
this will result that gcc can't find the definition of smp_store_release.

Let's place "<asm/barrier.h>" in "<asm/bitops.h>" just like what other
archs do.

This is to fix the compile warning as below:

  CC      arch/microblaze/kernel/asm-offsets.s
In file included from ./include/linux/rculist.h:10,
                 from ./include/linux/pid.h:5,
                 from ./include/linux/sched.h:14,
                 from arch/microblaze/kernel/asm-offsets.c:13:
./include/linux/list.h: In function 'list_del_init_careful':
./include/linux/list.h:300:2: error: implicit declaration of function 'smp_store_release' [-Werror=implicit-function-declaration]
  300 |  smp_store_release(&entry->next, entry);
      |  ^~~~~~~~~~~~~~~~~
./include/linux/list.h: In function 'list_empty_careful':
./include/linux/list.h:318:27: error: implicit declaration of function 'smp_load_acquire' [-Werror=implicit-function-declaration]
  318 |  struct list_head *next = smp_load_acquire(&head->next);
      |                           ^~~~~~~~~~~~~~~~
./include/linux/list.h:318:27: warning: initialization of 'struct list_head *' from 'int' makes pointer from integer without a cast [-Wint-conversion]

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>