drm: xlnx: fb: Guard with CONFIG_DRM_FBDEV_EMULATION
The fbdev emulation is optional, but the xlnx_fb fails to build
when CONFIG_DRM_FBDEV_EMULATION is disabled.

   drivers/gpu/drm/xlnx/xlnx_fb.c: In function 'xlnx_fbdev_defio_fini':
>> drivers/gpu/drm/xlnx/xlnx_fb.c:298:10: error: 'struct fb_info' has no member named 'fbdefio'
     298 |  if (!fbi->fbdefio)
         |          ^~
   drivers/gpu/drm/xlnx/xlnx_fb.c:302:11: error: 'struct fb_info' has no member named 'fbdefio'
     302 |  kfree(fbi->fbdefio);
         |           ^~

Disable some fbdev only functions using #ifdef CONFIG_DRM_FBDEV_EMULATION,
and move functions to re-group.

While at it remove one unused macro, XLNX_MAX_PLANES.

Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Hyun Kwon <hyun.kwon@xilinx.com>
Tested-by: Dylan Yip <dylan.yip@xilinx.com>