spi: Move update_stripe definition to spi-mem
After the introduction of update_stripe in e12fac290, when
MTD_SPI_NOR=m and MTD_M25P80=m, the following error is seen:

drivers/spi/spi-mem.o: In function `spi_mem_exec_op':
spi-mem.c:(.text+0x524): undefined reference to `update_stripe'

Move the definition of update_stripe to the module where it is used and
remove the declaration in spi.h.

Signed-off-by: Nicholas Graumann <nick.graumann@gmail.com>
Reviewed-by: Naga Sureshkumar Relli <naga.sureshkumar.relli@xilinx.com>
Signed-off-by: Michal Simek <michal.simek@xilinx.com>