misc: xilinx-ai-engine: Add condition compilation flag
Add condition compilation flag for aie_part_pin_user_region()
function in order to resolve below build error for allmodconfig.

"drivers/misc/xilinx-ai-engine/ai-engine-part.c:307:12:
error: 'aie_part_pin_user_region' defined but not used
[-Werror=unused-function]".

Signed-off-by: Satpute Sandeep <sandeep.satpute@amd.com>
Signed-off-by: Radhey Shyam Pandey <radhey.shyam.pandey@amd.com>
State: pending