usb: dwc3: define dummy dwc3_gadget_*_hibernation APIs for DWC3_HOST mode
dwc3_gadget_exit_hibernation() is called in dwc3 core.c but defined
in gadget sources. It results in the below compilation error when
DWC3 is configured for host only mode. To fix it define dummy
dwc3 gadget hibernation() APIs for host only mode.

aarch64-xilinx-linux-ld.real: drivers/usb/dwc3/core.o: in function
`dwc3_remove':
core.c:(.text+0x5c0): undefined reference to `dwc3_gadget_exit_hibernation'
aarch64-xilinx-linux-ld.real: drivers/usb/dwc3/core.o: in function
`dwc3_suspend':
core.c:(.text+0x8b0): undefined reference to `dwc3_gadget_exit_hibernation'

Signed-off-by: Radhey Shyam Pandey <radhey.shyam.pandey@amd.com>