dt-bindings: iio: adc: versal-sysmon: Remove deprecated header inclusion
The commit 658a0e39dc01 ("xilinx: Move all DT binding headers to dt
folder") moved xlnx-versal-regnode.h to an arch-specific location,
causing the binding example compilation to fail with:
error: dt-bindings/power/xlnx-versal-regnode.h: No such file or directory

Define PM_REGNODE_SYSMON_ROOT_0 locally in the example section and remove
the header inclusion.

Signed-off-by: Sai Krishna Potthuri <sai.krishna.potthuri@amd.com>
Message-ID: <20260304150100.2713460-4-sai.krishna.potthuri@amd.com>
State: pending