kbuild: Fix xilinx_puf.h uapi
When CONFIG_UAPI_HEADER_TEST is enabled and make usr/include/ is called
errors regarding unknown types are shown.

./usr/include/misc/xilinx_puf.h:34:9: error: unknown type name 'u8'
   34 |         u8 pufoperation;
...

That's why reference linux/types.h header which defines them.

Signed-off-by: Michal Simek <michal.simek@amd.com>