net: emacps: Fix CONFIG_XILINX_PS_EMAC_HWTSTAMP=y
Fix compilation issue:
drivers/net/ethernet/xilinx/xilinx_emacps.c: In function
'xemacps_time_keep':
drivers/net/ethernet/xilinx/xilinx_emacps.c:1040:2: error: implicit
declaration of function 'timecounter_read'
[-Werror=implicit-function-declaration]

by adding missing header.
This patch is untested on HW.

Signed-off-by: Michal Simek <michal.simek@xilinx.com>