uapi: rsmu: Fix unknown type name error
Update the type defined bool to _Bool.

   In file included from <built-in>:1:
>> ./usr/include/linux/rsmu.h:88:2: error: unknown type name 'bool'
      88 |         bool continuous;
         |         ^

bool is mistaken by headers since this is uapi and it is not included in
include/linux/types.h but in include/uapi/linux/types.h. In this case
bool is not a variable type which should be used in UAPIs. UAPI are
headers exported by kernel for userspace/toolchain to use the same
structures or types for communication, but here they have created UAPI
but none actually used it.

Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202501110003.PwZyO9m1-lkp@intel.com/
Signed-off-by: Abin Joseph <abin.joseph@amd.com>
Message-ID: <20250129181728.3171607-1-abin.joseph@amd.com>
State: pending