video: xylonfb: Add missing header
It should be the part of patch
"Merge tag 'v3.9' into master-next"
(sha1: 79a6cbd54869ed374f0d4ac6f2627c399b9eb34e)

The patch fix compilation errors:
drivers/video/xylon/xylonfb/of/../core/../misc/xylonfb-adv7511.c:220:1:
 error: unknown type name 'irqreturn_t'
drivers/video/xylon/xylonfb/of/../core/../misc/xylonfb-adv7511.c:228:9:
 error: 'IRQ_HANDLED' undeclared (first use in this function)
...

Signed-off-by: Michal Simek <michal.simek@xilinx.com>