usb: dwc3: Export symbol dwc3_host_wakeup_register/capable
Incase Generic xHCI platform device and xilinx dwc3 controller drivers
are enabled as module there is a need to export the host_wakeup_* func()
to the fix below error.

MODPOST Module.symvers
ERROR: modpost: "dwc3_host_wakeup_capable"
[drivers/usb/host/xhci-plat-hcd.ko] undefined!
ERROR: modpost: "dwc3_host_wakeup_register"
[drivers/usb/dwc3/dwc3-xilinx.ko] undefined!

Fixes: 2790ed87f0ae ("usb: dwc3: Add power management support in DWC3 Xilinx driver")
Signed-off-by: Radhey Shyam Pandey <radhey.shyam.pandey@amd.com>