firmware: xilinx: Add zynqmp_pm_get_node_status() API
Add zynqmp_pm_get_node_status() API which is being used by xilinx
zynqmp_r5_remoteproc driver to request a node's current power state.
Fixes below compilation error:

drivers/remoteproc/zynqmp_r5_remoteproc.c: In function 'sram_mem_release':
drivers/remoteproc/zynqmp_r5_remoteproc.c:188:31: error: implicit
declaration of function 'zynqmp_pm_get_node_status';
did you mean 'zynqmp_pm_reset_get_status'?
[-Werror=implicit-function-declaration]
  188 |ret = zynqmp_pm_get_node_status(pnode_id, &status, NULL, &usage);
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~
      |      zynqmp_pm_reset_get_status
drivers/remoteproc/zynqmp_r5_remoteproc.c:
In function 'xlnx_rpu_pm_request_sram':
drivers/remoteproc/zynqmp_r5_remoteproc.c:459:41:
error: 'PM_USAGE_NO_MASTER' undeclared (first use in this function)
  459 |                 if (!versal || usage == PM_USAGE_NO_MASTER) {
      |                                         ^~~~~~~~~~~~~~~~~~

Signed-off-by: Rajan Vaja <rajan.vaja@xilinx.com>
Signed-off-by: Radhey Shyam Pandey <radhey.shyam.pandey@amd.com>
State: not-upstreamable