staging: pmods: Fix missing SPI dependency
Compilation error reported by Kbuild:
   drivers/built-in.o: In function `screen_buf_to_display':
   pmodoled-gpio.c:(.text+0x2428a2): undefined reference to `spi_sync'
   pmodoled-gpio.c:(.text+0x2428fe): undefined reference to `spi_sync'
   drivers/built-in.o: In function `gpio_pmodoled_spi_remove':
   pmodoled-gpio.c:(.text+0x2429cd): undefined reference to `spi_sync'
   drivers/built-in.o: In function `gpio_pmodoled_spi_probe':
   pmodoled-gpio.c:(.text+0x242c34): undefined reference to `spi_setup'
   drivers/built-in.o: In function `gpio_pmodoled_of_probe':
>> pmodoled-gpio.c:(.text+0x243145): undefined reference to
>> `spi_busnum_to_master'
>> pmodoled-gpio.c:(.text+0x24317d): undefined reference to
>> `spi_alloc_device'
>> pmodoled-gpio.c:(.text+0x2431fe): undefined reference to
>> `spi_add_device'
>> pmodoled-gpio.c:(.text+0x243307): undefined reference to
>> `spi_register_driver'
   drivers/built-in.o: In function `gpio_pmodoled_disp_init':
   pmodoled-gpio.c:(.text.unlikely+0x26a5): undefined reference to
`spi_sync'
   pmodoled-gpio.c:(.text.unlikely+0x2733): undefined reference to
`spi_sync'
   pmodoled-gpio.c:(.text.unlikely+0x27ae): undefined reference to
`spi_sync'
   drivers/built-in.o:(.data+0x4851c): undefined reference to
`spi_bus_type'

Signed-off-by: Michal Simek <michal.simek@xilinx.com>