drm: xlnx: mmi-dc: Add missing bitfield.h include
Add the missing linux/bitfield.h header which provides the FIELD_PREP()
macro used in dc_dai_hw_params() function.

Without this include, the build fails with:

  drivers/gpu/drm/xlnx/mmi_dc_audio.c:150:15: error: implicit declaration
  of function 'FIELD_PREP' [-Werror=implicit-function-declaration]

Fixes: 5f20294b2852 ("drm: xlnx: mmi-dc: Implement non-live audio support")
Reported-by: Bhanu Teja Yadav Perugu <byadavpe@amd.com>
Reviewed-by: Vishal Sagar <vishal.sagar@amd.com>
Signed-off-by: Michal Simek <michal.simek@amd.com>
Message-ID: <8171d6c109b90fc43642f510e0df9e0b0312dc38.1775574311.git.michal.simek@amd.com>
State: pending