microblaze: Fix issue with msi compilation
There are some missing references to linux/irq.h.

Warning log:
arch/microblaze/pci/msi.c: In function 'create_irq':
arch/microblaze/pci/msi.c:59:2: error: implicit declaration of function
'dynamic_irq_init' [-Werror=implicit-function-declaration]
  dynamic_irq_init(irq);
  ^
arch/microblaze/pci/msi.c: In function 'destroy_irq':
arch/microblaze/pci/msi.c:76:2: error: implicit declaration of function
'dynamic_irq_cleanup' [-Werror=implicit-function-declaration]
  dynamic_irq_cleanup(irq);
  ^
arch/microblaze/pci/msi.c: At top level:
arch/microblaze/pci/msi.c:107:15: error: variable 'xilinx_msi_chip' has
initializer but incomplete type
 static struct irq_chip xilinx_msi_chip = {
               ^
arch/microblaze/pci/msi.c:108:3: error: unknown field 'name' specified
in initializer
   .name = "PCI-MSI",
   ^
arch/microblaze/pci/msi.c:108:3: warning: excess elements in struct
initializer [enabled by default]
arch/microblaze/pci/msi.c:108:3: warning: (near initialization for
'xilinx_msi_chip') [enabled by default]
arch/microblaze/pci/msi.c:109:3: error: unknown field 'irq_ack'
specified in initializer
   .irq_ack = xilinx_msi_nop,
   ^
arch/microblaze/pci/msi.c:109:3: warning: excess elements in struct
initializer [enabled by default]
arch/microblaze/pci/msi.c:109:3: warning: (near initialization for
'xilinx_msi_chip') [enabled by default]
arch/microblaze/pci/msi.c:110:3: error: unknown field 'irq_enable'
specified in initializer
   .irq_enable = unmask_msi_irq,
   ^
...

Signed-off-by: Michal Simek <michal.simek@xilinx.com>