mtd: rawnand: arasan: Simplify driver logic
The patch is initialize dma_mode, write_size, addrcycles variables which is
reported as
error: uninitialized symbol 'dma_mode'.
error: uninitialized symbol 'write_size'.
error: uninitialized symbol 'addrcycles'.

And also simplify logic around these variable.

Signed-off-by: Michal Simek <michal.simek@xilinx.com>
Tested-by: Naga Sureshkumar Relli <naga.sureshkumar.relli@xilinx.com>