media: xilinx-scaler: Add missing header
Add slab.h to resolve compilation error:
drivers/media/platform/xilinx/xilinx-scaler.c: In function
'xscaler_set_coefs':
drivers/media/platform/xilinx/xilinx-scaler.c:159:2: error: implicit
declaration of function 'kcalloc'
[-Werror=implicit-function-declaration]
  coef = kcalloc(phases, sizeof(*coef), GFP_KERNEL);
  ^
drivers/media/platform/xilinx/xilinx-scaler.c:159:7: warning: assignment
makes pointer from integer without a cast [enabled by default]
  coef = kcalloc(phases, sizeof(*coef), GFP_KERNEL);
       ^
drivers/media/platform/xilinx/xilinx-scaler.c:190:2: error: implicit
declaration of function 'kfree' [-Werror=implicit-function-declaration]
  kfree(coef);
  ^

Signed-off-by: Michal Simek <michal.simek@xilinx.com>