ARM64: zynqmp: Fix tap_delay conditional build
tap_delays.c depends on CONFIG_SOC_XILINX_ZYNQMP
not on ARCH_ZYNQMP directly.

There is compilation error when CONFIG_SOC_XILINX_ZYNQMP is
disabled and ARCH_ZYNQMP is enabled.

Error log:
drivers/soc/xilinx/zynqmp/tap_delays.c:244:6: error: redefinition of
'arasan_zynqmp_set_tap_delay'
 void arasan_zynqmp_set_tap_delay(u8 deviceid, u8 timing, u8 bank)
      ^
In file included from drivers/soc/xilinx/zynqmp/tap_delays.c:22:0:
include/linux/soc/xilinx/zynqmp/tap_delays.h:29:13: note: previous
definition of 'arasan_zynqmp_set_tap_delay' was here
 inline void arasan_zynqmp_set_tap_delay(u8 deviceid, u8 timing, u8
bank) {}
             ^
drivers/soc/xilinx/zynqmp/tap_delays.c:284:6: error: redefinition of
'zynqmp_dll_reset'
 void zynqmp_dll_reset(u8 deviceid)
      ^
In file included from drivers/soc/xilinx/zynqmp/tap_delays.c:22:0:
include/linux/soc/xilinx/zynqmp/tap_delays.h:30:13: note: previous
definition of 'zynqmp_dll_reset' was here
 inline void zynqmp_dll_reset(u8 deviceid) {}
             ^

Reported-by: Cyril Chemparathy <cyrilc@xilinx.com>
Signed-off-by: Michal Simek <michal.simek@xilinx.com>